[request_definition]
r = roles, obj, act, new

[policy_definition]
p = role, obj_type, act, obj_constraints, act_constraints, eft

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj.type == p.obj_type && r.act == p.act && \
    match_role(r.roles, p.role) && match_object(r.obj, p.obj_constraints) && match_constrains(r.new, p.act_constraints)