MAX_NUMBER_OF_ACTIVE_DB_SESSIONS = 25
TIME_OUT_FOR_QUERY = 60*5
MLFLOW_CLEANUP = 60*60
NUMBER_OF_ITEMS_TO_DRAIN = 300
EXECUTION_CAP_FOR_MAINMENUURLS = 5
BASE_URL = "http://bigpanda.cern.ch"
TIMEOUT_WHEN_DB_LOADED = 5
URL_WITH_BIG_TASKS = '/tasks/?site=ORNL_Titan_MCORE&status=running&json'
URL_WITH_ES_TASKS = '/tasks/?eventservice=eventservice&json'
HARVESTER_LIST_URL = '/harvesters/?json'
LOG_PATH = "/data/wenaus/bigpandamon_virtualhosts/twrpm/logs/cachecontroller.log"
PANDA_LOGGER_PATH = "/cephfs/atlpan/filebrowser"
MAX_LOG_AGE_DAYS = 3
PANDA_LOGGER_PATH_ANALYTICS = "/cephfs/atlpan/pandajoblogs"
MAX_LOG_AGE_DAYS_ANALYTICS = 14